name: Reusable Build

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  build:
    permissions:
      packages: write
    outputs:
      imageName: ${{ fromJson(steps.build-push.outputs.metadata)['image.name'] }}
      digest: ${{ steps.build-push.outputs.digest }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build-push
        with:
          push: ${{ inputs.push }}
          tags: ghcr.io/mathiassjacobsen/github-actions-workshop:latest
